### ISSUE TITLE
Local test case does not work for me

### ISSUE THREAD

**Issue by oumys** [dwslab/melt#121]
Hello,
 I tried to test locally the ontology alignment systems published on OAEI 2020 using MELT Evaluation Client
 on masCos Catalina 10.15.7. 
I started by testing anatomy track , this test case pass. However I tried to test it locally using :
**"java -jar matching-eval-client-3.1-SNAPSHOT.jar -s 2020/AML.zip 2020/LogMap.zip --local-testcase human.owl  mouse.owl reference.rdf -r MELTResults"**
I have this exception message:
**Exception in thread "main" java.lang.NullPointerException
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner.runMatcher(ExecutionRunner.java:48)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:193)
	at de.uni_mannheim.informatik.dws.melt.matching_eval_client.Main.main(Main.java:171)**

I  What is wrong with my command please to discover what is wrong with my command please.

Thanks you for your help.

**Comment by janothan** [comment]
Hi @oumys, thank you for reporting this issue. 
We can reproduce the problem and have submitted a bug fix.

Could you please [download the latest client](https://github.com/dwslab/melt/tree/evaluation-client/jar) and re-try?
If this works for you, please close the issue.

Best regards,
Jan
