### ISSUE TITLE
Empty rdf Files while testing tar.gz file using MatcherYAAAOwlApi

### ISSUE THREAD

**Issue by alisea47** [dwslab/melt#122]
Hi, I met another problem. Could u please take a look?

I modify `simpleWebMatcher ` project using **MatcherYAAAOwlApi**. I add dependency to `pom.xml` like this:
```
        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-distribution</artifactId>
            <version>5.1.9</version>
        </dependency>
```

After package it to `simplewebmatchertestowlapi-1.0-web.tar.gz`, I used `EvaluationExample ` case 3 to check it. However, a problem happened. My rdf file is empty and here is the whole log file:
```
2021-08-26 09:30:04 INFO  [main                          ] 171  in MatcherDockerFile    - Starting container from image simplewebmatchertestowlapi-1.0-web (port 8080 from container is mapped to port 49374 in host)
2021-08-26 09:30:07 INFO  [main                          ] 182  in MatcherDockerFile    - Container started with id 7808b1c4654a0695b35486f401a8a321e9fef05e098fbfac6e6efb0265c595d0
2021-08-26 09:30:07 INFO  [main                          ] 184  in MatcherDockerFile    - To see log output of container, run: docker container logs 7808b1c4654a
2021-08-26 09:30:07 INFO  [main                          ] 125  in Track                - Track cache folder is: C:\Users\84917\oaei_track_cache
2021-08-26 09:30:07 INFO  [main                          ] 48   in ExecutionRunner      - Running matcher Docker Matcher on testcase confof-sigkdd (track conference).
2021-08-26 09:30:09 INFO  [main                          ] 149  in MatcherHTTPCall      - Execute now the following HTTP request: POST http://localhost:49374/match HTTP/1.1
2021-08-26 09:30:10 INFO  [main                          ] 64   in ExecutionRunner      - Running matcher Docker Matcher on testcase confof-sigkdd (track conference) completed in 2 seconds.
2021-08-26 09:30:11 ERROR [main                          ] 145  in ExecutionResult      - The system alignment given by following URL could not be parsed: file:/C:/Users/84917/AppData/Local/Temp/alignment9002698976025933244.rdf
org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:196)
	at de.uni_mannheim.informatik.dws.melt.yet_another_alignment_api.AlignmentParser.parse(AlignmentParser.java:101)
	at de.uni_mannheim.informatik.dws.melt.yet_another_alignment_api.AlignmentParser.parse(AlignmentParser.java:84)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionResult.silentlyParseAlignment(ExecutionResult.java:140)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionResult.getSystemAlignment(ExecutionResult.java:176)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV.getAlignmentExtensions(EvaluatorCSV.java:184)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV.<init>(EvaluatorCSV.java:146)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV.<init>(EvaluatorCSV.java:202)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV.<init>(EvaluatorCSV.java:211)
	at de.uni_mannheim.informatik.dws.melt.demomatcher.EvaluationExample.main(EvaluationExample.java:62)
2021-08-26 09:30:11 INFO  [main                          ] 228  in EvaluatorCSV         - Evaluate matcher Docker Matcher
2021-08-26 09:30:11 INFO  [main                          ] 81   in OntologyCacheJena    - Reading model into cache (file:/C:/Users/84917/oaei_track_cache/oaei.webdatacommons.org/conference/conference-v1/confof-sigkdd/source.rdf)
2021-08-26 09:30:12 INFO  [main                          ] 81   in OntologyCacheJena    - Reading model into cache (file:/C:/Users/84917/oaei_track_cache/oaei.webdatacommons.org/conference/conference-v1/confof-sigkdd/target.rdf)
2021-08-26 09:30:12 INFO  [main                          ] 48   in ExecutionRunner      - Running matcher baseLineMatcher on testcase confof-sigkdd (track conference).
2021-08-26 09:30:12 INFO  [main                          ] 64   in ExecutionRunner      - Running matcher baseLineMatcher on testcase confof-sigkdd (track conference) completed in 0 seconds.
2021-08-26 09:30:12 INFO  [main                          ] 237  in EvaluatorCSV         - Writing alignment cube
2021-08-26 09:30:12 INFO  [main                          ] 124  in AlignmentsCube       - Writing conference | confof-sigkdd | Docker Matcher [to file: D:\code\java\eclipse\simpleWebMatcher\results\results_2021-08-26_09-30-11\alignmentCube.csv]
The time is 10249 ms
```
My `java version: 1.8.0_301`, By the way, I'm not sure if the versionof dependency is right or not.
Here is the project: [https://zafueducn-my.sharepoint.com/:f:/g/personal/19930003_zafu_edu_cn/EudJQezo5qZMlJKYCeQQizUBR9yEWALXvtqSqubM0KbD-g?e=jf6Fze](https://zafueducn-my.sharepoint.com/:f:/g/personal/19930003_zafu_edu_cn/EudJQezo5qZMlJKYCeQQizUBR9yEWALXvtqSqubM0KbD-g?e=jf6Fze)

Thank u very much!

**Comment by sven-h** [comment]
Hi @alisea47 
if you want to use `MatcherYAAAOwlApi` you need the dependency

```
<dependency>
      <groupId>de.uni-mannheim.informatik.dws.melt</groupId>
      <artifactId>matching-owlapi</artifactId>
      <version>${matching.version}</version>
</dependency> 
```

which is included transitively if you have `matching-eval` inlcuded as well (without the `test` scope).
The reason why we put `matching-eval` in `test` scope is to reduce the number of dependencies when packaging the matcher.
Thus they are not included.

Changing the version is done as you showed. Just change `<matching.version>3.0</matching.version>` to `<matching.version>3.1</matching.version>` .

Best regards
Sven

**Comment by janothan** [comment]
Hi @alisea47, if the answer provided by Sven solved your issue, please close it 🙂

**Comment by sven-h** [comment]
Please reopen this issue in case it still persists.
