### ISSUE TITLE
Error Evaluationcsv

### ISSUE THREAD

**Issue by mnikp** [dwslab/melt#128]
When I want to evaluate a matcher, for example logmap, in the running there is some errors as below: I am not sure that is it a problem or not because the alignmentCube.csv has been saved in the result folder.

ERROR EvaluatorCSV         - Could not write detailed evaluation file.

...MELTREsultslltc\LocalTrack_1.0\aggregated\http:\localhost:8080\match\aggregatedPerformance.csv (The filename, directory name, or volume label syntax is incorrect)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at org.apache.commons.csv.CSVFormat.print(CSVFormat.java:1196)
        at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV.writeAggregatedFileMatcherTrack(EvaluatorCSV.java:336)
        at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV.writeResultsToDirectory(EvaluatorCSV.java:238)
        at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.Evaluator.writeToDirectory(Evaluator.java:90)
        at de.uni_mannheim.informatik.dws.melt.matching_eval_client.Main.main(Main.java:202)

**Comment by sven-h** [comment]
Hi,

the reason for that error is the following part of the file path: LocalTrack_1.0\aggregated\ **http:\localhost:8080\match** \aggregatedPerformance.csv

This is usually the name of the matcher (the subfolders of `aggregated`).

How do you run the matchers? With java code or the evaluation client etc?

How is the matcher wrapped? Web(Docker), Seals, etc?

If you run it by code, please share the corresponding java file with us.

Best regards
Sven

**Comment by sven-h** [comment]
Hi,

we looked further into your issue and found that this is probably a bug in the EvaluatorCSV class.
We already fixed it. Can you try it out once again using the latest master commit or the [latest evaluation client](https://nightly.link/dwslab/melt/workflows/java_client_upload/master/evaluation-client.zip)

Best regards
Sven

**Comment by mnikp** [comment]
Hi,
The latest evaluation client run the command without any error.
Thank you.
