### ISSUE TITLE
getting java: incompatible types

### ISSUE THREAD

**Issue by abhiseksharma** [dwslab/melt#188]
Hi,

In the latest version of MELT, while running python matcher through "EvaluateDemoPythonMatcher.java", I'm getting "java: incompatible types: java.util.Map<java.lang.String,java.lang.String> cannot be converted to java.util.Map<java.lang.String,java.lang.Object>"
in "EvaluatorBasic.java" at "extensionValues = determineExtensionValuesToWriteForCSV(er.getSystemAlignment().getExtensions()); (line 89)".

The above error started from "protected Map<String, String> extensions;" line inside "Alignment.class".

Tried some things but nothing worked. 
Kindly suggest what can we do to resolve this.

Thanks,
Abhisek Sharma

**Comment by sven-h** [comment]
Hi Abhisek,

[yet-another-alignment-api](https://mvnrepository.com/artifact/de.uni-mannheim.informatik.dws.melt/yet-another-alignment-api)

can you check if you use the same version for all MELT related packages such as [`mathcing-eval`, `matching-base`, `matching-jena`, or `yet-another-alignment-api`](https://mvnrepository.com/artifact/de.uni-mannheim.informatik.dws.melt).
We changed the type of the correspondence extensions, but this was (hopefully) done consistently (therefore different versions might be the reason).

In case this does not solve your problem, can you provide a small example where the error happens?

Best regards
Sven

**Comment by abhiseksharma** [comment]
It worked after your suggested changes. Thanks.

Kindly take a look at the below error:
`[main] INFO de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner - Running matcher demo on testcase iasted-sigkdd (track conference) completed in 1 second.
[main] INFO de.uni_mannheim.informatik.dws.melt.demomatcher.EvaluateDemoPythonMatcher - Python matcher run returned 0 correspondences.
[main] INFO de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV - Evaluate matcher demo
[main] INFO de.uni_mannheim.informatik.dws.melt.matching_jena.OntologyCacheJena - Reading model into cache (file:/C:/Users/abhis/oaei_track_cache/oaei.webdatacommons.org/conference/conference-v1/ekaw-iasted/source.rdf)
[main] INFO de.uni_mannheim.informatik.dws.melt.matching_jena.OntologyCacheJena - Reading model into cache (file:/C:/Users/abhis/oaei_track_cache/oaei.webdatacommons.org/conference/conference-v1/ekaw-iasted/target.rdf)
[main] INFO de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner - Running matcher baseLineMatcher on testcase ekaw-iasted (track conference).
[main] ERROR de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner - Exception during matching (matcher baseLineMatcher on testcase ekaw-iasted).
de.uni_mannheim.informatik.dws.melt.matching_base.typetransformer.TypeTransformationException: No transformation route is found between [class java.net.URL] to class java.util.Properties
	at de.uni_mannheim.informatik.dws.melt.matching_base.typetransformer.TypeTransformerRegistry.getClassTransformationRouteMultipleRepresentations(TypeTransformerRegistry.java:350)
	at de.uni_mannheim.informatik.dws.melt.matching_base.typetransformer.TypeTransformerRegistry.getClassTransformationRoute(TypeTransformerRegistry.java:252)
	at de.uni_mannheim.informatik.dws.melt.matching_base.typetransformer.TypeTransformerRegistry.getObjectTransformationRoute(TypeTransformerRegistry.java:189)
	at de.uni_mannheim.informatik.dws.melt.matching_base.typetransformer.TypeTransformerRegistry.getObjectTransformationRoute(TypeTransformerRegistry.java:184)
	at de.uni_mannheim.informatik.dws.melt.matching_base.typetransformer.TypeTransformerRegistry.getTransformedObject(TypeTransformerRegistry.java:545)
	at de.uni_mannheim.informatik.dws.melt.matching_base.typetransformer.GenericMatcherCaller.runIMatcher(GenericMatcherCaller.java:300)
	at de.uni_mannheim.informatik.dws.melt.matching_base.typetransformer.GenericMatcherCaller.runMatcherMultipleRepresentations(GenericMatcherCaller.java:151)
	at de.uni_mannheim.informatik.dws.melt.matching_base.typetransformer.GenericMatcherCaller.runMatcher(GenericMatcherCaller.java:76)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner.runMatcher(ExecutionRunner.java:101)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner.runMatcher(ExecutionRunner.java:75)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.runSingle(Executor.java:59)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.refinement.ResidualRefiner.refine(ResidualRefiner.java:72)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionResultSet.get(ExecutionResultSet.java:91)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV.writeOverviewFileMatcherTestCase(EvaluatorCSV.java:470)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV.writeResultsToDirectory(EvaluatorCSV.java:239)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.Evaluator.writeToDirectory(Evaluator.java:90)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.Evaluator.writeToDirectory(Evaluator.java:75)
	at de.uni_mannheim.informatik.dws.melt.demomatcher.EvaluateDemoPythonMatcher.main(EvaluateDemoPythonMatcher.java:26)
[main] INFO de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner - Running matcher baseLineMatcher on testcase ekaw-iasted (track conference) completed in 0 seconds.
[main] ERROR de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner - Matching task unsuccessful: output alignment equals null. (matcher: baseLineMatcher testcase: ekaw-iasted track: conference)
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at java.base/java.util.Collections$SetFromMap.add(Collections.java:5566)
	at com.googlecode.cqengine.persistence.support.CollectionWrappingObjectStore.add(CollectionWrappingObjectStore.java:84)
	at com.googlecode.cqengine.ConcurrentIndexedCollection.add(ConcurrentIndexedCollection.java:359)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.refinement.ResidualRefiner.refine(ResidualRefiner.java:73)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionResultSet.get(ExecutionResultSet.java:91)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV.writeOverviewFileMatcherTestCase(EvaluatorCSV.java:470)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.EvaluatorCSV.writeResultsToDirectory(EvaluatorCSV.java:239)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.Evaluator.writeToDirectory(Evaluator.java:90)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.evaluator.Evaluator.writeToDirectory(Evaluator.java:75)
	at de.uni_mannheim.informatik.dws.melt.demomatcher.EvaluateDemoPythonMatcher.main(EvaluateDemoPythonMatcher.java:26)

Process finished with exit code 1
`

Thanks
Abhisek

**Comment by sven-h** [comment]
How do you execute it?
With custom code or with the eval client?
Can you maybe provide a small example which produces the error?

**Comment by abhiseksharma** [comment]
Hi Sven, 

I was trying to run through eval client. I created a docker image and was testing on conference track. It was working fine on other tracks i.e., anatomy, etc. But giving this error over conference track.

Thanks
Abhisek

**Comment by sven-h** [comment]
Hi Abhisek,

can you please provide the exact command line which you executed and maybe even the docker image?
Maybe also the one which works and the one which doesn't work.

Best regards
Sven

**Comment by sven-h** [comment]
in case the error still exists, please open another issue
